apiVersion: argoproj.io/v1alpha1
kind: Application          
metadata:
  name: app-of-apps-child
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  source:
    path: app-of-apps/guestbook
    repoURL: https://github.com/jannfis/openshift-test-apps
  syncPolicy:
    automated:
      prune: true
